version: '3.8'
services:
  backend:
    image: ghcr.io/innatical/skye-backend:main
    environment:
      - DATABASE_URL_FILE=/run/secrets/skye_database_url
      - JWT_KEY_FILE=/run/secrets/skye_jwt_key
      - FEDERAION_KEY_FILE=/run/secrets/skye_federation_key
    ports:
      - '3006:3000'
    secrets:
      - skye_database_url
      - skye_jwt_key
      - skye_federation_key
secrets:
  skye_database_url:
    external: true
  skye_jwt_key:
    external: true
  skye_federation_key:
    external: true
